### ISSUE TITLE
Deprecated BatchV1beta1Api

### ISSUE THREAD

**Issue by djerfy** [djerfy/zabbix-kubernetes-discovery#10]
Error on a Kubernetes v1.25

```text
Traceback (most recent call last):
  File "/app/zabbix-kubernetes-discovery.py", line 125, in <module>
    zabbix.send(zabbixDiscoveryCronjob(args.kubernetes_name, getCronjob(args.object_name, args.exclude_name, args.exclude_namespace)))))
  File "/app/modules/kubernetes/get.py", line 267, in getCronjob
    kubernetes = client.BatchV1beta1Api()
AttributeError: module 'kubernetes.client' has no attribute 'BatchV1beta1Api'
```

**Comment by djerfy** [comment]
Done via 71e34176dad06d1c093f6258e815aec25dcdd6ad
