### ISSUE TITLE
Bug with cronjob items

### ISSUE THREAD

**Issue by djerfy** [djerfy/zabbix-kubernetes-discovery#12]
Error during item cronjob execution:

```text
Traceback (most recent call last):
  File "/app/zabbix-kubernetes-discovery.py", line 128, in <module>
    zabbix.send(zabbixItemCronjob(args.kubernetes_name, getCronjob(args.object_name, args.exclude_name, args.exclude_namespace)))))
  File "/app/modules/zabbix/item.py", line 97, in zabbixItemCronjob
    sender.append(ZabbixMetric(clustername, f"kubernetes.cronjob.exitcode[{cronjob['namespace']},{cronjob['name']}]", cronjob['status']['status']['exitcode']),)
KeyError: 'status'
```

Changes from BatchV1beta1Api to BatchV1Api...

**Comment by djerfy** [comment]
Cronjob fixed:

```text
JSON output (cronjob): [{'name': 'cronjob-test-ok', 'namespace': 'default', 'status': '0', 'last_job': {'name': 'cronjob-test-ok-27896875', 'reason': None, 'message': None, 'status': 'Complete'}}, {'name': 'cronjob-test-ko', 'namespace': 'default', 'status': '1', 'last_job': {'name': 'cronjob-test-ko-27896875', 'reason': 'BackoffLimitExceeded', 'message': 'Job has reached the specified backoff limit', 'status': 'Failed'}}]
```

Ready for the next release

**Comment by djerfy** [comment]
Version 1.4.5 released
